/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdventureRouteImport } from './routes/adventure'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as ParentIndexRouteImport } from './routes/parent.index'
import { Route as ParentSubscriptionRouteImport } from './routes/parent.subscription'
import { Route as PlayAreaRouteImport } from './routes/play.$area'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdventureRoute = AdventureRouteImport.update({
  id: '/adventure',
  path: '/adventure',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentIndexRoute = ParentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParentRoute,
} as any)
const ParentSubscriptionRoute = ParentSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => ParentRoute,
} as any)
const PlayAreaRoute = PlayAreaRouteImport.update({
  id: '/play/$area',
  path: '/play/$area',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adventure': typeof AdventureRoute
  '/parent': typeof ParentRouteWithChildren
  '/rewards': typeof RewardsRoute
  '/parent/subscription': typeof ParentSubscriptionRoute
  '/play/$area': typeof PlayAreaRoute
  '/parent/': typeof ParentIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adventure': typeof AdventureRoute
  '/rewards': typeof RewardsRoute
  '/parent/subscription': typeof ParentSubscriptionRoute
  '/play/$area': typeof PlayAreaRoute
  '/parent': typeof ParentIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adventure': typeof AdventureRoute
  '/parent': typeof ParentRouteWithChildren
  '/rewards': typeof RewardsRoute
  '/parent/subscription': typeof ParentSubscriptionRoute
  '/play/$area': typeof PlayAreaRoute
  '/parent/': typeof ParentIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adventure'
    | '/parent'
    | '/rewards'
    | '/parent/subscription'
    | '/play/$area'
    | '/parent/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adventure'
    | '/rewards'
    | '/parent/subscription'
    | '/play/$area'
    | '/parent'
  id:
    | '__root__'
    | '/'
    | '/adventure'
    | '/parent'
    | '/rewards'
    | '/parent/subscription'
    | '/play/$area'
    | '/parent/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdventureRoute: typeof AdventureRoute
  ParentRoute: typeof ParentRouteWithChildren
  RewardsRoute: typeof RewardsRoute
  PlayAreaRoute: typeof PlayAreaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventure': {
      id: '/adventure'
      path: '/adventure'
      fullPath: '/adventure'
      preLoaderRoute: typeof AdventureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/': {
      id: '/parent/'
      path: '/'
      fullPath: '/parent/'
      preLoaderRoute: typeof ParentIndexRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/subscription': {
      id: '/parent/subscription'
      path: '/subscription'
      fullPath: '/parent/subscription'
      preLoaderRoute: typeof ParentSubscriptionRouteImport
      parentRoute: typeof ParentRoute
    }
    '/play/$area': {
      id: '/play/$area'
      path: '/play/$area'
      fullPath: '/play/$area'
      preLoaderRoute: typeof PlayAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ParentRouteChildren {
  ParentSubscriptionRoute: typeof ParentSubscriptionRoute
  ParentIndexRoute: typeof ParentIndexRoute
}

const ParentRouteChildren: ParentRouteChildren = {
  ParentSubscriptionRoute: ParentSubscriptionRoute,
  ParentIndexRoute: ParentIndexRoute,
}

const ParentRouteWithChildren =
  ParentRoute._addFileChildren(ParentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdventureRoute: AdventureRoute,
  ParentRoute: ParentRouteWithChildren,
  RewardsRoute: RewardsRoute,
  PlayAreaRoute: PlayAreaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
