/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdventureRouteImport } from './routes/adventure'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as WorldsRouteImport } from './routes/worlds'
import { Route as GameGameIdRouteImport } from './routes/game.$gameId'
import { Route as ParentIndexRouteImport } from './routes/parent.index'
import { Route as ParentChildrenRouteImport } from './routes/parent.children'
import { Route as ParentCmsRouteImport } from './routes/parent.cms'
import { Route as ParentRightsRouteImport } from './routes/parent.rights'
import { Route as ParentSubscriptionRouteImport } from './routes/parent.subscription'
import { Route as PlayAreaRouteImport } from './routes/play.$area'
import { Route as WorldWorldIdRouteImport } from './routes/world.$worldId'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdventureRoute = AdventureRouteImport.update({
  id: '/adventure',
  path: '/adventure',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldsRoute = WorldsRouteImport.update({
  id: '/worlds',
  path: '/worlds',
  getParentRoute: () => rootRouteImport,
} as any)
const GameGameIdRoute = GameGameIdRouteImport.update({
  id: '/game/$gameId',
  path: '/game/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentIndexRoute = ParentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParentRoute,
} as any)
const ParentChildrenRoute = ParentChildrenRouteImport.update({
  id: '/children',
  path: '/children',
  getParentRoute: () => ParentRoute,
} as any)
const ParentCmsRoute = ParentCmsRouteImport.update({
  id: '/cms',
  path: '/cms',
  getParentRoute: () => ParentRoute,
} as any)
const ParentRightsRoute = ParentRightsRouteImport.update({
  id: '/rights',
  path: '/rights',
  getParentRoute: () => ParentRoute,
} as any)
const ParentSubscriptionRoute = ParentSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => ParentRoute,
} as any)
const PlayAreaRoute = PlayAreaRouteImport.update({
  id: '/play/$area',
  path: '/play/$area',
  getParentRoute: () => rootRouteImport,
} as any)
const WorldWorldIdRoute = WorldWorldIdRouteImport.update({
  id: '/world/$worldId',
  path: '/world/$worldId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adventure': typeof AdventureRoute
  '/parent': typeof ParentRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/rewards': typeof RewardsRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/worlds': typeof WorldsRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/parent/children': typeof ParentChildrenRoute
  '/parent/cms': typeof ParentCmsRoute
  '/parent/rights': typeof ParentRightsRoute
  '/parent/subscription': typeof ParentSubscriptionRoute
  '/play/$area': typeof PlayAreaRoute
  '/world/$worldId': typeof WorldWorldIdRoute
  '/parent/': typeof ParentIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adventure': typeof AdventureRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/rewards': typeof RewardsRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/worlds': typeof WorldsRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/parent/children': typeof ParentChildrenRoute
  '/parent/cms': typeof ParentCmsRoute
  '/parent/rights': typeof ParentRightsRoute
  '/parent/subscription': typeof ParentSubscriptionRoute
  '/play/$area': typeof PlayAreaRoute
  '/world/$worldId': typeof WorldWorldIdRoute
  '/parent': typeof ParentIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adventure': typeof AdventureRoute
  '/parent': typeof ParentRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/rewards': typeof RewardsRoute
  '/terms': typeof TermsRoute
  '/welcome': typeof WelcomeRoute
  '/worlds': typeof WorldsRoute
  '/game/$gameId': typeof GameGameIdRoute
  '/parent/children': typeof ParentChildrenRoute
  '/parent/cms': typeof ParentCmsRoute
  '/parent/rights': typeof ParentRightsRoute
  '/parent/subscription': typeof ParentSubscriptionRoute
  '/play/$area': typeof PlayAreaRoute
  '/world/$worldId': typeof WorldWorldIdRoute
  '/parent/': typeof ParentIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adventure'
    | '/parent'
    | '/privacy'
    | '/refund'
    | '/rewards'
    | '/terms'
    | '/welcome'
    | '/worlds'
    | '/game/$gameId'
    | '/parent/children'
    | '/parent/cms'
    | '/parent/rights'
    | '/parent/subscription'
    | '/play/$area'
    | '/world/$worldId'
    | '/parent/'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adventure'
    | '/privacy'
    | '/refund'
    | '/rewards'
    | '/terms'
    | '/welcome'
    | '/worlds'
    | '/game/$gameId'
    | '/parent/children'
    | '/parent/cms'
    | '/parent/rights'
    | '/parent/subscription'
    | '/play/$area'
    | '/world/$worldId'
    | '/parent'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/adventure'
    | '/parent'
    | '/privacy'
    | '/refund'
    | '/rewards'
    | '/terms'
    | '/welcome'
    | '/worlds'
    | '/game/$gameId'
    | '/parent/children'
    | '/parent/cms'
    | '/parent/rights'
    | '/parent/subscription'
    | '/play/$area'
    | '/world/$worldId'
    | '/parent/'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdventureRoute: typeof AdventureRoute
  ParentRoute: typeof ParentRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  RewardsRoute: typeof RewardsRoute
  TermsRoute: typeof TermsRoute
  WelcomeRoute: typeof WelcomeRoute
  WorldsRoute: typeof WorldsRoute
  GameGameIdRoute: typeof GameGameIdRoute
  PlayAreaRoute: typeof PlayAreaRoute
  WorldWorldIdRoute: typeof WorldWorldIdRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adventure': {
      id: '/adventure'
      path: '/adventure'
      fullPath: '/adventure'
      preLoaderRoute: typeof AdventureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worlds': {
      id: '/worlds'
      path: '/worlds'
      fullPath: '/worlds'
      preLoaderRoute: typeof WorldsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/game/$gameId': {
      id: '/game/$gameId'
      path: '/game/$gameId'
      fullPath: '/game/$gameId'
      preLoaderRoute: typeof GameGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent/': {
      id: '/parent/'
      path: '/'
      fullPath: '/parent/'
      preLoaderRoute: typeof ParentIndexRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/children': {
      id: '/parent/children'
      path: '/children'
      fullPath: '/parent/children'
      preLoaderRoute: typeof ParentChildrenRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/cms': {
      id: '/parent/cms'
      path: '/cms'
      fullPath: '/parent/cms'
      preLoaderRoute: typeof ParentCmsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/rights': {
      id: '/parent/rights'
      path: '/rights'
      fullPath: '/parent/rights'
      preLoaderRoute: typeof ParentRightsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/subscription': {
      id: '/parent/subscription'
      path: '/subscription'
      fullPath: '/parent/subscription'
      preLoaderRoute: typeof ParentSubscriptionRouteImport
      parentRoute: typeof ParentRoute
    }
    '/play/$area': {
      id: '/play/$area'
      path: '/play/$area'
      fullPath: '/play/$area'
      preLoaderRoute: typeof PlayAreaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/world/$worldId': {
      id: '/world/$worldId'
      path: '/world/$worldId'
      fullPath: '/world/$worldId'
      preLoaderRoute: typeof WorldWorldIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ParentRouteChildren {
  ParentChildrenRoute: typeof ParentChildrenRoute
  ParentCmsRoute: typeof ParentCmsRoute
  ParentRightsRoute: typeof ParentRightsRoute
  ParentSubscriptionRoute: typeof ParentSubscriptionRoute
  ParentIndexRoute: typeof ParentIndexRoute
}

const ParentRouteChildren: ParentRouteChildren = {
  ParentChildrenRoute: ParentChildrenRoute,
  ParentCmsRoute: ParentCmsRoute,
  ParentRightsRoute: ParentRightsRoute,
  ParentSubscriptionRoute: ParentSubscriptionRoute,
  ParentIndexRoute: ParentIndexRoute,
}

const ParentRouteWithChildren =
  ParentRoute._addFileChildren(ParentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdventureRoute: AdventureRoute,
  ParentRoute: ParentRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  RewardsRoute: RewardsRoute,
  TermsRoute: TermsRoute,
  WelcomeRoute: WelcomeRoute,
  WorldsRoute: WorldsRoute,
  GameGameIdRoute: GameGameIdRoute,
  PlayAreaRoute: PlayAreaRoute,
  WorldWorldIdRoute: WorldWorldIdRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
